// automatically generated by the FlatBuffers compiler, do not modify

package teste

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Armor struct {
	_tab flatbuffers.Table
}

func GetRootAsArmor(buf []byte, offset flatbuffers.UOffsetT) *Armor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Armor{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Armor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Armor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Armor) Equipment(obj *Equipment) *Equipment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Equipment)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Armor) Bonus() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Armor) MutateBonus(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func ArmorStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ArmorAddEquipment(builder *flatbuffers.Builder, equipment flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(equipment), 0)
}
func ArmorAddBonus(builder *flatbuffers.Builder, bonus int32) {
	builder.PrependInt32Slot(1, bonus, 0)
}
func ArmorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
