// automatically generated by the FlatBuffers compiler, do not modify

package teste

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Powerups struct {
	_tab flatbuffers.Table
}

func GetRootAsPowerups(buf []byte, offset flatbuffers.UOffsetT) *Powerups {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Powerups{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Powerups) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Powerups) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Powerups) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Powerups) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PowerupsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PowerupsAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PowerupsAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(description), 0)
}
func PowerupsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
