// automatically generated by the FlatBuffers compiler, do not modify

package teste

const (
	RarityCommon = 0
	RarityUncommon = 1
	RarityRare = 2
)

var EnumNamesRarity = map[int]string{
	RarityCommon:"Common",
	RarityUncommon:"Uncommon",
	RarityRare:"Rare",
}

